language: go
matrix:
  include:
    - go: 1.11.x
    - go: 1.12.x
    - go: 1.13.x
    - go: 1.14.x
    - go: 1.15.x
      env: LATEST=true
    - go: tip
  allow_failures:
    - go: tip

install:
  - export GO111MODULE=on
  - go get -t -v ./...

script:
  - go test -tags=ci -v ./...
  - if [ "${LATEST}" = "true" ]; then
      GOOS=darwin GOARCH=amd64 go build -ldflags "-s -w" -o monday-darwin-amd64 ./cmd &&
      GOOS=darwin GOARCH=arm go build -ldflags "-s -w" -o monday-darwin-arm ./cmd &&
      GOOS=linux GOARCH=386 go build -ldflags "-s -w" -o monday-linux-386 ./cmd &&
      GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -o monday-linux-amd64 ./cmd &&
      GOOS=linux GOARCH=arm go build -ldflags "-s -w" -o monday-linux-arm ./cmd
    fi

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file:
    - monday-darwin-amd64
    - monday-darwin-arm
    - monday-linux-386
    - monday-linux-amd64
    - monday-linux-arm
  on:
    repo: eko/monday
    tags: true
    condition: $LATEST = true
