name: Test (master)

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: [ '1.20' ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go_version }}

      - name: Run tests
        shell: script -q -e -c "bash {0}"
        run: |
          export TERM=xterm
          go test -v -cover -tags=ci ./...
