name: Test (master)

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: [ '1.12', '1.13', '1.14', '1.15' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go_version }}

      - name: Install go dependencies & run tests
        shell: script -q -e -c "bash {0}"
        run: |
          export TERM=xterm
          go get -t -v ./...
          go test -v -cover -tags=ci ./...
